import type {
  ChatMessage,
  Inspection,
  Property,
  Rental,
  Renter,
  Subscription,
  Vehicle,
} from "./types";

export const vehicleChecklist = [
  "Exterior body panels and paint",
  "Windshield, mirrors, lights",
  "Tires, rims, spare kit",
  "Interior seats and upholstery",
  "Dashboard warnings and controls",
  "Brakes, steering, suspension",
  "Fuel level and charging cable",
  "Registration, insurance, road kit",
];

export const propertyChecklist = [
  "Doors, locks, keys, access devices",
  "Walls, floors, windows, curtains",
  "Kitchen appliances and cabinets",
  "Bathroom fixtures and ventilation",
  "Heating, cooling, water pressure",
  "Electrical outlets and lighting",
  "Furniture, inventory, remote controls",
  "Smoke detectors, permits, safety kit",
];

export const seedSubscriptions: Subscription[] = [
  {
    module: "vehicles",
    tier: "scale",
    active: true,
    seats: 8,
    renewalDate: "2026-06-17",
    monthlyPrice: 149,
  },
  {
    module: "properties",
    tier: "starter",
    active: true,
    seats: 4,
    renewalDate: "2026-06-17",
    monthlyPrice: 129,
  },
];

export const seedVehicles: Vehicle[] = [
  {
    id: "veh-001",
    make: "Mercedes-Benz",
    model: "Vito Tourer",
    year: 2024,
    plate: "ZG-482-LT",
    vin: "W1V44770513822991",
    status: "rented",
    location: "Zagreb Airport",
    className: "Executive van",
    dayRate: 145,
    odometer: 18420,
    fuel: 72,
    insuranceProvider: "Croatia Osiguranje",
    insurancePolicy: "CO-8842-26",
    insuranceExpires: "2026-11-05",
    registrationExpires: "2026-09-18",
    inspectionDue: "2026-05-24",
    serviceDue: "2026-07-12",
    conditionScore: 94,
    utilization: 82,
    revenueMonth: 6840,
    features: ["8 seats", "Automatic", "Airport ready", "GPS tracker"],
    photos: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-v1", title: "Insurance policy", status: "valid", expires: "2026-11-05" },
      { id: "doc-v2", title: "Registration", status: "valid", expires: "2026-09-18" },
      { id: "doc-v3", title: "Service book", status: "review", expires: "2026-07-12" },
    ],
    notes: "Premium airport transfer unit. Requires interior photo set after each return.",
  },
  {
    id: "veh-002",
    make: "Tesla",
    model: "Model Y Long Range",
    year: 2025,
    plate: "ST-921-EV",
    vin: "7SAYGDEE3PF652441",
    status: "available",
    location: "Split City Garage",
    className: "Electric SUV",
    dayRate: 169,
    odometer: 7320,
    fuel: 88,
    insuranceProvider: "Generali",
    insurancePolicy: "GE-EV-3510",
    insuranceExpires: "2027-01-20",
    registrationExpires: "2026-12-30",
    inspectionDue: "2026-06-02",
    serviceDue: "2026-10-14",
    conditionScore: 98,
    utilization: 68,
    revenueMonth: 5120,
    features: ["Electric", "Panoramic roof", "App unlock", "Child seat"],
    photos: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-v4", title: "Insurance policy", status: "valid", expires: "2027-01-20" },
      { id: "doc-v5", title: "Charging adapter inventory", status: "valid" },
    ],
    notes: "Keep charge above 80 percent before handoff. Include charging guide in chat.",
  },
  {
    id: "veh-003",
    make: "Volkswagen",
    model: "Crafter L3H2",
    year: 2023,
    plate: "RI-447-KA",
    vin: "WV1ZZZSYZP9031447",
    status: "maintenance",
    location: "Rijeka Depot",
    className: "Cargo van",
    dayRate: 119,
    odometer: 41210,
    fuel: 41,
    insuranceProvider: "Allianz",
    insurancePolicy: "AL-CV-9018",
    insuranceExpires: "2026-08-09",
    registrationExpires: "2026-06-28",
    inspectionDue: "2026-05-19",
    serviceDue: "2026-05-29",
    conditionScore: 86,
    utilization: 74,
    revenueMonth: 4380,
    features: ["Cargo rails", "Tail camera", "Manual", "Moving kit"],
    photos: [
      "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1596572523028-07c8e2b617c2?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-v6", title: "Insurance policy", status: "valid", expires: "2026-08-09" },
      { id: "doc-v7", title: "Repair estimate", status: "review" },
    ],
    notes: "Rear bumper scratch logged. Do not release until repair signoff is complete.",
  },
];

export const seedProperties: Property[] = [
  {
    id: "prop-001",
    name: "Marina View Residence",
    type: "Apartment",
    address: "Obala kneza Branimira 12, Zadar",
    status: "rented",
    monthlyRent: 1840,
    deposit: 2500,
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 86,
    occupancy: 96,
    inspectionDue: "2026-05-27",
    insuranceExpires: "2026-10-01",
    permitExpires: "2027-02-14",
    conditionScore: 92,
    revenueMonth: 1840,
    amenities: ["Sea view", "Parking", "Smart lock", "Furnished"],
    photos: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-p1", title: "Property insurance", status: "valid", expires: "2026-10-01" },
      { id: "doc-p2", title: "Tourism permit", status: "valid", expires: "2027-02-14" },
    ],
    notes: "Long-stay tenant. Balcony rail photos required at quarterly inspection.",
  },
  {
    id: "prop-002",
    name: "Upper Town Studio",
    type: "Studio",
    address: "Mesnicka 7, Zagreb",
    status: "available",
    monthlyRent: 980,
    deposit: 1300,
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 38,
    occupancy: 81,
    inspectionDue: "2026-06-03",
    insuranceExpires: "2026-09-15",
    permitExpires: "2026-12-20",
    conditionScore: 97,
    revenueMonth: 980,
    amenities: ["City center", "Work desk", "Washer", "Self check-in"],
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-p3", title: "Property insurance", status: "valid", expires: "2026-09-15" },
      { id: "doc-p4", title: "Energy certificate", status: "valid" },
    ],
    notes: "Ready for monthly lease. Add new mattress protector before move-in.",
  },
  {
    id: "prop-003",
    name: "Logistics Yard Unit B",
    type: "Commercial",
    address: "Industrijska cesta 22, Osijek",
    status: "inspection",
    monthlyRent: 3100,
    deposit: 5000,
    bedrooms: 0,
    bathrooms: 2,
    squareMeters: 420,
    occupancy: 64,
    inspectionDue: "2026-05-20",
    insuranceExpires: "2026-08-22",
    permitExpires: "2026-11-09",
    conditionScore: 84,
    revenueMonth: 3100,
    amenities: ["Loading dock", "CCTV", "Office", "Truck access"],
    photos: [
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1100&q=80",
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1100&q=80",
    ],
    documents: [
      { id: "doc-p5", title: "Facility insurance", status: "valid", expires: "2026-08-22" },
      { id: "doc-p6", title: "Fire safety report", status: "review", expires: "2026-05-25" },
    ],
    notes: "Schedule fire door repair before next commercial handoff.",
  },
];

export const seedRenters: Renter[] = [
  {
    id: "ren-001",
    name: "Luka Marino",
    company: "Adria Events",
    email: "luka@adriaevents.example",
    phone: "+385 91 442 1882",
    verified: true,
    riskScore: 12,
    licenseId: "HR-440218-M",
    paymentMethod: "Visa ending 1042",
  },
  {
    id: "ren-002",
    name: "Nina Kovac",
    email: "nina.kovac@example.com",
    phone: "+385 98 221 718",
    verified: true,
    riskScore: 8,
    licenseId: "HR-998421-K",
    paymentMethod: "SEPA mandate",
  },
  {
    id: "ren-003",
    name: "Mateo Shipping d.o.o.",
    company: "Mateo Shipping",
    email: "ops@mateoshipping.example",
    phone: "+385 51 338 210",
    verified: false,
    riskScore: 31,
    paymentMethod: "Invoice net 7",
  },
];

export const seedRentals: Rental[] = [
  {
    id: "rent-001",
    module: "vehicles",
    assetId: "veh-001",
    renterId: "ren-001",
    startDate: "2026-05-16",
    endDate: "2026-05-22",
    status: "active",
    price: 870,
    deposit: 650,
    balanceDue: 0,
    pickupLocation: "Zagreb Airport",
    returnLocation: "Zagreb Airport",
    contractStatus: "signed",
    channel: "Direct",
    checkInInspectionId: "ins-001",
  },
  {
    id: "rent-002",
    module: "properties",
    assetId: "prop-001",
    renterId: "ren-002",
    startDate: "2026-05-01",
    endDate: "2026-09-01",
    status: "active",
    price: 7360,
    deposit: 2500,
    balanceDue: 1840,
    pickupLocation: "Digital check-in",
    returnLocation: "Digital check-out",
    contractStatus: "signed",
    channel: "Owner portal",
    checkInInspectionId: "ins-002",
  },
  {
    id: "rent-003",
    module: "vehicles",
    assetId: "veh-002",
    renterId: "ren-003",
    startDate: "2026-05-25",
    endDate: "2026-05-28",
    status: "confirmed",
    price: 507,
    deposit: 900,
    balanceDue: 507,
    pickupLocation: "Split City Garage",
    returnLocation: "Split City Garage",
    contractStatus: "sent",
    channel: "Partner API",
  },
];

export const seedInspections: Inspection[] = [
  {
    id: "ins-001",
    module: "vehicles",
    assetId: "veh-001",
    rentalId: "rent-001",
    type: "pre",
    date: "2026-05-16",
    inspector: "Ana Topic",
    status: "complete",
    odometer: 18104,
    fuel: 94,
    photos: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80",
    ],
    signature: "Luka Marino",
    checks: vehicleChecklist.map((label, index) => ({
      id: `veh-check-${index}`,
      label,
      result: index === 2 ? "watch" : "pass",
      notes: index === 2 ? "Minor wear on rear right rim photographed." : "",
    })),
    followUps: ["Compare rear right rim after return."],
  },
  {
    id: "ins-002",
    module: "properties",
    assetId: "prop-001",
    rentalId: "rent-002",
    type: "pre",
    date: "2026-05-01",
    inspector: "Petar Simic",
    status: "complete",
    meterReading: "Electric 18402 kWh, Water 991 m3",
    photos: [
      "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=900&q=80",
    ],
    signature: "Nina Kovac",
    checks: propertyChecklist.map((label) => ({
      id: `prop-check-${label}`,
      label,
      result: "pass",
      notes: "",
    })),
    followUps: ["Quarterly balcony rail photo set."],
  },
];

export const seedMessages: ChatMessage[] = [
  {
    id: "msg-001",
    rentalId: "rent-001",
    sender: "RentPilot Ops",
    role: "operator",
    body: "Your Vito is ready at Zagreb Airport. The pre-rental inspection and signed contract are attached to this rental.",
    timestamp: "2026-05-16T08:45:00.000Z",
  },
  {
    id: "msg-002",
    rentalId: "rent-001",
    sender: "Luka Marino",
    role: "renter",
    body: "Thanks. We found the van and will upload a photo of the luggage area before departure.",
    timestamp: "2026-05-16T09:02:00.000Z",
  },
  {
    id: "msg-003",
    rentalId: "rent-002",
    sender: "RentPilot Homes",
    role: "operator",
    body: "Welcome to Marina View Residence. Smart lock access was enabled and the move-in checklist is complete.",
    timestamp: "2026-05-01T13:20:00.000Z",
  },
];
